# Page settings

baseURL = "http://curriculum.ferran.co/"
languageCode = "es"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = ""






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#000000"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ferran Arroyo"
        tagline = "Data Scientist"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Madrid"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "622318401"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "ferran_arroyo@hotmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.ferran.co"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Lenguajes de programación"
        [[params.skills.list.items]]
        details = "R"
        [[params.skills.list.items]]
        details = "Python"

        [[params.skills.list]]
        title = "Conocimiento técnico"
        [[params.skills.list.items]]
        details = "Machine Learning"
        [[params.skills.list.items]]
        details = "Estadística"
        [[params.skills.list.items]]
        details = "Programación"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Microsoft Professional Program on Data Science"
        university = "Microsoft Academy"
        dates = "2016 - 2016"
        [[params.education.list]]
        degree = "Master en Data Science"
        university = "MBIT School"
        dates = "2015 - 2016"
        [[params.education.list]]
        degree = "Licenciatura en Ciencias Acturiales y Financieras"
        university = "Universitat de Barcelona"
        dates = "2010 - 2013"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Castellano"
        level = "Nativo"
        [[params.languages.list]]
        name = "Catalán"
        level = "Nativo"
        [[params.languages.list]]
        name = "Inglés"
        level = "Profesional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Machine Learning"
        [[params.interests.list]]
        name = "Deep Learning"
        [[params.interests.list]]
        name = "Inversion en dominios"
        [[params.interests.list]]
        name = "Criptomonedas y tecnología Blockchain"
        [[params.interests.list]]
        name = "Creación de páginas web"
        [[params.interests.list]]
        name = "Nuevas Tecnologías"






    [params.summary]
        enable = true
        text = "Soy licenciado en Ciencias Actuariales, y tengo un Master en Data Science por MBIT School, así como la certificación del Microsoft Professional Program en Data Science. He pasado por un amplio abanico de nomenclaturas laborales relacionadas con el dato, como Actuario, Data Analyst, Data Miner y Data Scientist (actualmente). Mi experiencia trabajando con datos es superior a los 10 años. He trabajado, y trabajo en grandes compañías del sector asegurador español donde participo en distintos proyectos de datos para la aplicación del Machine Learning con el objetivo de la optimización y mejora de los distintos procesos de la compañías. Soy un apasionado de todo lo que envuelve a la tecnología blockchain y de las aplicaciones prácticas que tiene. Mi otra gran pasión tiene que ver con el mundo de los dominios y, al igual que con las criptomonedas, parte de mi cartera de inversión la tengo diversificada en este tipo de activos digitales."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Data Scientist"
        dates = "2016 - Presente"
        company = "AXA"
        details = "Integrado en el equipo de Data Scientists del departamento de Big Data | Behavioral Pricing, las funciones más importantes que realizo son:"
        [[params.experience.list.items]]
        details = "Creación, implementación y mantenimiento de distintos modelos de negocio de la compañía, tales como el Market Prediction, Churn Behaviour o Cross-Selling."
        [[params.experience.list.items]]
        details = "Creación, implementación y mantenimiento de distintos dashboards para el análisis y seguimiento del negocio."

        [[params.experience.list]]
        title = "Data Scientist"
        dates = "2015 - 2016"
        company = "Aegon-Santander"
        details = "Integrado en el departamento técnico, las funciones más relevantes del puesto fueron:"
        [[params.experience.list.items]]
        details = "Creación, implementación y mantenimiento de Modelo Predictivo de Fraude para la optimización en la investigación."
        [[params.experience.list.items]]
        details = "Creación, implementación y mantenimiento de Modelo Descriptivo para la elaboración de nuevas tablas de preexistencia optimizadas."

        [[params.experience.list]]
        title = "Data Analyst"
        dates = "2012 - 2015"
        company = "Fidias Actuarios"
        details = "Formando parte del equipo de actuarios de la consultora, las funciones más relevantes del puesto fueron:"
        [[params.experience.list.items]]
        details = "Modelización predictiva para elaboración de artículos técnicos de pensiones."
        [[params.experience.list.items]]
        details = "Peritación judicial.Cálculo del lucro cesante y daño emergente."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Curso de inversión en criptomonedas y NFT de cero a experto"
        meta = "Formación"
        tagline = "Curso para aprender a invertir mediante las mejores estrategias en activos criptográficos como Bitcoin, Ethereum o los NFTs en Udemy."

        [[params.projects.list]]
        title = "Knowledge Trends"
        meta = "Emprendimiento"
        tagline = "Comunidad de instructores de Udemy."









    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        #[[params.social.list]]
        #icon = "fab fa-github-square"
        #url = "//github.com/username"
        #title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/actuariodatascientist"
        title = ""
        #[[params.social.list]]
        #icon = "fab fa-twitter-square"
        #url = "//twitter.com/username"
        #title = "@username"
